# Generated by Django 2.0.6 on 2018-06-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friends', models.ManyToManyField(blank=True, null=True, related_name='_bloguser_friends_+', to='blog.BlogUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
