# Generated by Django 2.0.6 on 2018-06-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180619_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.BlogUser'),
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
