# Generated by Django 2.0.6 on 2018-06-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='post',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_by_user', to='blog.Comment'),
            preserve_default=False,
        ),
    ]
