# Generated by Django 2.0.6 on 2018-06-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180619_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='comment',
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_comment_by_user', to='blog.Post'),
            preserve_default=False,
        ),
    ]
